---
title: "CorrigeDataCamp"
output: html_document
date: "2026-04-13"
author: "Andrea Vandirek Romero"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Carga de librerías
library(tidyverse)
library(lubridate)
library(knitr)
```

**Trabajo Corrección automática de tareas de Datacamp**

Objetivo: Desarrollar un programa que permita realizar la corrección automática de una tarea de Datacamp y asigne a cada alumno la puntuación obtenida. 

```{r}
# se buscan todos los ficheros de puntuaciones
puntos_fichero <- list.files("Alumnos/.", pattern = "puntos.txt", full.names = FALSE, recursive = TRUE)

# se buscan todos los ficheros con el justificante del curso
justificante_fichero <- list.files("Alumnos/.", pattern = "certificate.pdf", full.names = FALSE, recursive = TRUE)


# extraccion de apellidos de los alumnos
apellidos <- list.files("Alumnos/.", full.names = FALSE, recursive = TRUE) %>%
            strsplit(split = ',', fixed = TRUE) %>%
            map_chr(1) %>%
            unique()


```

